spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_mybrary
    username: root
    password : 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

kakao:
  api:
    key: ${KAKAO_API_KEY}

eureka:
  client:
    enabled: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace