spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    config:
      enabled: false

kakao:
  api:
    key: test-kakao-key

aladin:
  api:
    key: test-aladin-key

eureka:
  client:
    enabled: false

logging:
  level:
    root: info
