spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mybrary-testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

kakao:
  api:
    key: ${KAKAO_API_KEY}

aladin:
  api:
    key: ${ALADIN_API_KEY}

eureka:
  client:
    enabled: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace