spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    sql:
      init:
        mode: never

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    config:
      enabled: false

logging:
  level:
    root: info

jwt:
  secretKey: testSecretKey1234567890abcdefghijk
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-Refresh
