spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/USER_DB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: mybrary_user
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

    sql:
      init:
        mode: never