### 1. 회원 가입
POST http://localhost:8080/sign-up
Content-Type: application/json

{
    "loginId": "id1",
    "password": "password1!",
    "email": "email1@naver.com",
    "nickname": "nickname1"
}

### 2. 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
    "loginId": "id11",
    "password": "password1!"
}

### 3. 소셜 로그인
GET http://localhost:8080/oauth2/authorization/google
