### 1. 회원 가입
POST http://localhost:8080/api/v1/users/sign-up
Content-Type: application/json

{
  "loginId": "loginId",
  "password": "password123!",
  "nickname": "nickname",
  "email": "email@email.com"
}

### 2. 회원 탈퇴
DELETE http://localhost:8080/api/v1/users/account
USER-ID: loginId

### 3. 로그인
POST http://43.200.200.185:8003/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "testId",
  "password": "password123!"
}

### 4. 로그아웃
POST http://localhost:8080/api/v1/auth/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImxvZ2luSWQiOiI3ZWFlM2QwZC0wYzU5LTQxMzctYWU5My1hYjhjOTZmNWZiMGUiLCJleHAiOjE2OTEyMTUyODh9.DkPQdLlegkCVONgElh9UoAr_YpmsX5Ci11TGzsYtVYtK9fHJ7ypjPXpVvMM_fEy1gnDtyjWz0Q9a0TcapedAmA

### 5. 인가 테스트
GET http://localhost:8080/auth/v1/test
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImxvZ2luSWQiOiI3ZWFlM2QwZC0wYzU5LTQxMzctYWU5My1hYjhjOTZmNWZiMGUiLCJleHAiOjE2OTEyMTUyODh9.DkPQdLlegkCVONgElh9UoAr_YpmsX5Ci11TGzsYtVYtK9fHJ7ypjPXpVvMM_fEy1gnDtyjWz0Q9a0TcapedAmA

### 6. 구글 소셜 로그인
GET http://localhost:8080/oauth2/authorization/google

### 7. 카카오 소셜 로그인
GET http://localhost:8080/oauth2/authorization/kakao

### 8. 네이버 소셜 로그인
GET http://localhost:8080/oauth2/authorization/naver

### 9. 인증 오류
GET http://localhost:8080/user/profile

### 10. 토큰 오류
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer invalidToken1234
Authorization-Refresh: Bearer invalidRefreshToken1234

### 11. 프로필 조회
GET http://localhost:8080/api/v1/users/loginId/profile

### 12. 프로필 수정
PUT http://localhost:8080/api/v1/users/loginId/profile
Content-Type: application/json
USER-ID: loginId

{
  "nickname": "new-nickname",
  "email": "new-email@mail.com",
  "introduction": "new-introduction"
}

### 13. 프로필 이미지 조회
GET http://localhost:8080/api/v1/users/loginId/profile/image

### 14. 프로필 이미지 삭제
DELETE http://localhost:8080/api/v1/users/loginId/profile/image
USER-ID: loginId

### 15. 사용자 검색
GET http://localhost:8080/api/v1/users/search?nickname=nick

### 16. 팔로워 조회
GET http://localhost:8080/api/v1/users/loginId2/followers

### 17. 팔로잉 조회
GET http://localhost:8080/api/v1/users/loginId/followings

### 18. 팔로우
POST http://localhost:8080/api/v1/users/follow
USER-ID: loginId
Content-Type: application/json

{
  "targetId": "loginId2"
}

### 19. 언팔로우
DELETE http://localhost:8080/api/v1/users/follow
USER-ID: loginId
Content-Type: application/json

{
  "targetId": "loginId2"
}

### 20. 팔로워 삭제
DELETE http://localhost:8080/api/v1/users/follower
USER-ID: loginId2
Content-Type: application/json

{
  "sourceId": "loginId"
}

### 21. 팔로잉 여부 조회
GET http://localhost:8080/api/v1/users/follow?targetId=loginId2
USER-ID: loginId

### 22. 카테고리별 관심사 모두 조회
GET http://localhost:8080/api/v1/interest-categories

### 23. 사용자 관심사 조회
GET http://localhost:8080/api/v1/users/loginId/interests

### 24. 사용자 관심사 업데이트
PUT http://localhost:8080/api/v1/users/loginId/interests
USER-ID: loginId
Content-Type: application/json

{
    "interestRequests": [
      {
        "id": 1,
        "name": "국내소설"
      },
      {
        "id": 2,
        "name": "외국소설"
      }
    ]
}

### 25. 사용자 정보 모두 조회
GET http://localhost:8080/api/v1/users/info
Content-Type: application/json

{
  "userIds": [
    "loginId1",
    "loginId2"
  ]
}