### 회원 가입
POST http://localhost:8000/user-service/api/v1/users/sign-up
Content-Type: application/json

{
  "loginId": "loginId",
  "password": "password123!",
  "nickname": "nickname",
  "email": "email@email.com"
}

### 로그인
POST http://localhost:8000/user-service/api/v1/auth/login
Content-Type: application/json

{
  "loginId": "loginId",
  "password": "password123!"
}

### 로그아웃
POST http://localhost:8000/user-service/api/v1/auth/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImxvZ2luSWQiOiJsb2dpbklkIiwiZXhwIjoxNjkyMDg5OTAxfQ.Y3t_mpjLGtqgifALZcmNkpNNZUtYY0ukSwhlpmM3hpeZYXsI7Fz0CuEDCsM3xYdCWwLPe6hyLJ4Rp_vfjl26Qw

### 인가 테스트
GET http://localhost:8000/user-service/auth/v1/test
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImxvZ2luSWQiOiJsb2dpbklkIiwiZXhwIjoxNjkyMDQwOTYwfQ.92lR7pwy88mhzGGY9d6HRz_LdaX_LsO6BRsySuam72VoGHOIAlGfqKTgFrSBaznuRlKzPXopRbKATmPIH7ymOA
Authorization-Refresh: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJSZWZyZXNoVG9rZW4iLCJleHAiOjE2OTMyOTExMzN9.lh7d-bJDVA4hdh0ePfcI9zFE3P9xJx5vtfdK-KLY5BQ4GnwRGhhJ1NhMZB1Nbvl3mHPc0IxwevGEEoVdT3-fEA

### 토큰 재발급
GET http://localhost:8000/user-service/auth/v1/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImxvZ2luSWQiOiJsb2dpbklkIiwiZXhwIjoxNjkyMDQwOTYwfQ.92lR7pwy88mhzGGY9d6HRz_LdaX_LsO6BRsySuam72VoGHOIAlGfqKTgFrSBaznuRlKzPXopRbKATmPIH7ymOA
Authorization-Refresh: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJSZWZyZXNoVG9rZW4iLCJleHAiOjE2OTMyOTgwMzJ9.t0Zq0YhH0254Us6q7E6UfxiMCajco6SAeHKMSrHCMxiojOxhWX_7j0-JMT7Exx9Y5U3V-SNaL-2cayJjnN4ANg

### 프로필 조회
GET http://localhost:8000/user-service/api/v1/users/loginId/profile

### 프로필 수정
PUT http://localhost:8000/user-service/api/v1/users/loginId/profile
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImxvZ2luSWQiOiJsb2dpbklkIiwiZXhwIjoxNjkyMDkyMTYwfQ.KH7tb1N3nZRaeHZkD_RBZpWhDGjTUrNn9Z36xQ9jhtkx4WCuNBaewOC3yBjYCh2uBO_Bp4GH20n3PyiTT28yHw

{
  "nickname": "new-nickname",
  "email": "new-email@mail.com",
  "introduction": "new-introduction"
}

### 사용자 검색
GET http://localhost:8000/user-service/api/v1/users/search?nickname=nick