spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/USER_DB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: mybrary_user
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    sql:
      init:
        mode: never

jwt:
  secretKey: uNZBk5i5P20/KnqGpv+siyWE1H0oQ1oBu9RaCJ84AsyDjvp73Gd+ML1K4yHXuqj2wck0sGqfIdQcjaI0ypI52A==

  access:
    expiration: 3600000 # 1시간
    header: Authorization

  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-Refresh