spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    kr.mybrary: info
