name: 'mybrary-server upload ecr & ecs'

on:
  push:
    branches:
      - master
    paths:
      - 'backend/mybrary-server/**'
  pull_request:
    branches:
      - master
    paths:
      - 'backend/mybrary-server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Application Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: backend/mybrary-server/src/main/resources/application.yml
        env:
          jwt.secretKey: ${{ secrets.JWT_SECRET_KEY }}
          spring.security.oauth2.client.registration.google.client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          spring.security.oauth2.client.registration.google.client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          spring.security.oauth2.client.registration.naver.client-id: ${{ secrets.NAVER_CLIENT_ID }}
          spring.security.oauth2.client.registration.naver.client-secret: ${{ secrets.NAVER_CLIENT_SECRET }}
          spring.security.oauth2.client.registration.kakao.client-id: ${{ secrets.KAKAO_CLIENT_ID }}
          spring.security.oauth2.client.registration.kakao.client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
          cloud.aws.credentials.access-key: ${{ secrets.AWS_ACCESS_KEY }}
          cloud.aws.credentials.secret-key: ${{ secrets.AWS_SECRET_KEY }}
          kakao.api.key: ${{ secrets.KAKAO_BOOK_API_KEY }}
          aladin.api.key: ${{ secrets.ALADIN_API_KEY }}

      - name: Test with Gradle
        working-directory: backend/mybrary-server
        run: |
          ./gradlew test -Dspring.profiles.active=test

      - name: Build with Gradle
        working-directory: backend/mybrary-server
        run: |
          ./gradlew clean build -x test -Dspring.profiles.active=prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ECS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_ECS_SECRET_KEY }}
          aws-region: ${{ secrets.ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_MYBRARY_SERVER_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        working-directory: backend/mybrary-server
        run: |
          docker build --platform amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ secrets.ECS_MYBRARY_SERVER_TASK_DEFINITION }} \
            --query taskDefinition \
            > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ secrets.ECS_MYBRARY_SERVER_CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_MYBRARY_SERVER_SERVICE }}
          cluster: ${{ secrets.ECS_MYBRARY_SERVER_CLUSTER }}
          wait-for-service-stability: true
